from . import training_course
from . import training_student
from . import training_enrollment
from . import trainer
from . import training_attendance
from . import training_payment
from . import training_payment_transaction
from . import training_dashboard_service
from . import res_config_settings
